import test, { Page} from "@playwright/test";

export async function navigateToMainPage(page: Page) {
    await page.goto("/");
  }


//for random email we can use specific library/create our own methig, depends of requirements
// for simplicyty i'm using this
export const  randomEmail = () => 
    {return Math.round(Math.random()*100000)+"@email.com"};

// assumption: page don't have validation for password strenght
// simple password generator - if we dont't need to use that random user after
// with knowledge that this is not proper password, that could be also generated by library
export const randomPassword = () => 
    {return Math.random().toString(36).slice(-8)};


